// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atgvasxcssuevrxczdms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0Z3Zhc3hjc3N1ZXZyeGN6ZG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjkzNTgsImV4cCI6MjA1ODE0NTM1OH0.5tWxdHl1vehkdfSId8eVulmRpW0T6xhdfRnWxnIx9rQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);